[package]
name = "rizz"
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace]
members = [
  "rizz_macros"
]

[dependencies]
rizz_macros = { path = "rizz_macros", version = "0.1.0" }
thiserror = { version = "1.0.48" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rusqlite = { version = "0.29.0", features = ["bundled"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.106" }
serde_rusqlite = { version = "0.33.1" }
tokio-rusqlite = { version = "0.4.0" }
